### ISSUE TITLE
The V1_LEGACY  RenderQueue Not work on DX11

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre-next#280] opened 2022-04-18 06:27 UTC
#### System Information
- Ogre Version: :grey_question: ogre-next master
- Operating System / Platform: :grey_question: Win10
- RenderSystem: :grey_question:DX11
- GPU: :grey_question:GTX960M

#### Detailled description

I Create a v1::Entity Object that use a material with a simpler shader, and  add it to a  V1_LEGACY  renderQueue,
It work fine with GL3, But throw exception with DX11,
The Exception place is at file "OgreD3D11RenderSystem"  line 3105。
The Exception msg is " ID3D11DeviceContext::DrawIndexed: The Pixel Shader expects a Render Target View bound to slot 0, but none is bound. This is OK, as writes of an unbound Render Target View are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Render Target View here. [ EXECUTION WARNING #3146081: DEVICE_DRAW_RENDERTARGETVIEW_NOT_SET]"

Below is the main code:

   Ogre::v1::Entity* ent = mOgreSceneMgr->createEntity(mesh, group, Ogre::SCENE_DYNAMIC);
    ent->setMaterialName("Editor/TransparentGrid");

   Ogre::SceneNode* node = mOgreSceneMgr->getRootSceneNode()->createChildSceneNode(Ogre::SCENE_DYNAMIC);

   node->attachObject(ent);

   ent->setRenderQueueGroup(226);
   mOgreSceneMgr->getRenderQueue()->setRenderQueueMode(ent->getRenderQueueGroup(), Ogre::RenderQueue::Modes::V1_LEGACY);

		
The material  "Editor/TransparentGrid" use a very  basic shader .

**Comment by darksylinc** [comment] 2022-04-18 14:24
This sounds like a bug.

**As a workaround:** Do you really need `V1_LEGACY`? `V1_FAST` supports Low Level Materials too for a long time now.

`V1_LEGACY` is only needed for _very_ specific behaviors.

You will likely just get what you want by using `V1_FAST`.

**Comment by darksylinc** [comment] 2022-04-25 00:12
Could you edit one of the samples (any of them) to repro the error so I can take a look? (i.e. a `git diff` patch would be enough; or just upload the modified files as a zip)

**Comment by 36yang** [comment] 2022-04-26 11:04
I now know the cause of the problem. I didn't provide a shadow shader. The exception thrown made me find the wrong direction of the problem.
But now It occasionally throw a new exception. At present, I can't reproduce it in samples. It will only appear occasionally in my program. Maybe it's other problems.
The new exception is:
   D3D11 device cannot draw indexed
Error Description:ID3D11DeviceContext::DrawIndexed: Draw cannot be invoked while a bound Resource is currently mapped. The Vertex Shader Constant Buffer at slot (2) is still mapped.


So, now I can only avoid using V1: entity and use a custom hlms to implement my functions

**Comment by darksylinc** [comment] 2022-04-26 15:14
Are you perhaps trying to use Ogre from 2 different threads? It sounds like a race condition.

The API is complaining a buffer is still mapped (i.e. there was no unmap call) and is needed by the draw

**Comment by 36yang** [comment] 2022-09-23 15:49
I recently found an error, which is the same as the previous problem. I reproduced this problem by modifying the PbsMaterials example. The following are the code and resources that I can reproduce this rendering exception after modifying. The modified code is correct, and you need to comment out some of them to reproduce the exception

**Comment by 36yang** [comment] 2022-09-23 15:52
[PbsMaterialsGameState.zip](https://github.com/OGRECave/ogre-next/files/9635174/PbsMaterialsGameState.zip)

**Comment by darksylinc** [comment] 2022-09-23 19:41
Hi,

Thanks for the repro.

This is not an OgreNext bug.

The problem is that mDirectionPointer is trying to cast a shadow; and the low material cannot handle this case well.

Hence it "tries to render to a colour map, but none is bound"; because the shadow map binds no colour map (except for point lights and ESM shadow maps).

Your problem can be fixed with:

`mDirectionPointer->setCastShadows( false );`

**Comment by darksylinc** [comment] 2022-09-23 19:48
> So, now I can only avoid using V1: entity and use a custom hlms to implement my functions

I just noticed what this comment means. It may be worth pointing out you CAN use Hlms and V1 objects (e.g. V1 Entitiy)

**Comment by 36yang** [comment] 2022-09-24 17:22
Thank you for your answer. My problem has been solved

**Closed** 2022-09-24 18:57 UTC
