### ISSUE TITLE
Error reading back from depth texture in Vulkan

### ISSUE THREAD

**Issue by jwwalker** [OGRECave/ogre-next#322] opened 2022-08-05 16:42 UTC
#### System Information
- Ogre Version: master branch as of 4 Aug 2022
- Operating System / Platform: Windows 11 Home, 21H2, 64 bit
- RenderSystem: Vulkan
- GPU: NVIDIA GeForce RTX 2060

#### Detailed description
When using Vulkan, rendering to a depth texture of pixel format `PFG_D32_FLOAT` and then reading it back to CPU memory just gives zeros.

To reproduce:

1. Start with the Test_Readback sample
2. Add `#include <sstream>` to ReadbackGameState.cpp
3. Replace the code of `ReadbackGameState::update` as follows:

```
    void ReadbackGameState::update( float timeSinceLast )
    {
        Ogre::TextureGpuManager *textureManager =
            mGraphicsSystem->getRoot()->getRenderSystem()->getTextureGpuManager();

        Ogre::TextureGpu *readbackTex = textureManager->createTexture(
            "Readback Tex", Ogre::GpuPageOutStrategy::Discard, Ogre::TextureFlags::RenderToTexture,
            Ogre::TextureTypes::Type2D );
        const Ogre::uint32 resolution = 96u;
        readbackTex->setResolution( resolution, resolution );
        readbackTex->setPixelFormat( Ogre::PFG_D32_FLOAT );
        readbackTex->scheduleTransitionTo( Ogre::GpuResidency::Resident );

        mGraphicsSystem->getSceneManager()->updateSceneGraph();

        Ogre::CompositorManager2 *compositorManager =
            mGraphicsSystem->getRoot()->getCompositorManager2();
        Ogre::CompositorWorkspace *workspace =
            compositorManager->addWorkspace( mGraphicsSystem->getSceneManager(), readbackTex,
                                             mGraphicsSystem->getCamera(), "Readback Workspace", false );

        workspace->_validateFinalTarget();
        workspace->_beginUpdate( false );
        workspace->_update();
        workspace->_endUpdate( false );

        Ogre::Image2 image;
        image.convertFromTexture( readbackTex, 0u, 0u );
        Ogre::TextureBox box = image.getData( 0u );

        float minVal = INFINITY;
        float maxVal = -INFINITY;
        const float *depths = static_cast<const float *>( box.data );
        for( Ogre::uint32 i = 0; i < resolution * resolution ; ++i)
        {
            float x = depths[i];
            if( x < minVal )
            {
                minVal = x;
            }
            if(x > maxVal)
            {
                maxVal = x;
            }
        }
        if(minVal < maxVal)
        {
            Ogre::LogManager::getSingleton().stream()
                << "Depth values range from " << minVal << " to " << maxVal;
        }
        else
        {
            Ogre::LogManager::getSingleton().stream() << "Depth values are all == " << minVal;
        }

        compositorManager->removeWorkspace( workspace );
        textureManager->destroyTexture( readbackTex );

        TutorialGameState::update( timeSinceLast );
    }
```

4. Build and run.

Then I see in the log repeats of this:

```
Ogre: ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdCopyImageToBuffer-aspectMask-00211 ] Object 0: handle = 0xfef35a00000000a0, name = Readback Tex, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x167672e0 | vkCmdCopyImageToBuffer: pRegion[0] subresource aspectMask 0x1 specifies aspects that are not present in image format 0x7e. The Vulkan spec states: For each element of pRegions, imageSubresource.aspectMask must specify aspects present in pname:srcImage (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdCopyImageToBuffer-aspectMask-00211)
Ogre: Depth values are all == 0
```

If I do this on a Mac with the Metal render system, the result is that the log repeatedly shows:

```
Depth values are all == 0.00940569
```

#### Analysis

`TextureGpuManager::createAsyncTextureTicket` passes the depth texture pixel format `PFG_D32_FLOAT` to `PixelFormatGpuUtils::getFamily` which chooses a pixel format family of `PFG_R32_UINT`. Later, when `VulkanMappings::getImageAspect` passes that family to `PixelFormatGpuUtils::getFlags`, the only flag that is returned is `PFF_INTEGER`, not `PFF_DEPTH`. As a result, `VulkanMappings::getImageAspect` returns `VK_IMAGE_ASPECT_COLOR_BIT` instead of `VK_IMAGE_ASPECT_DEPTH_BIT`.

#### Possible fixes

1. Maybe `PixelFormatGpuUtils::getFamily` could be modified to give `PFG_D32_FLOAT` a different family, perhaps grouped with `PFG_D32_FLOAT_S8X24_UINT`.  I don't have sufficient understanding of how `PixelFormatGpuUtils::getFamily` was constructed to know whether that would be a valid thing to do.
2. `VulkanAsyncTextureTicket::downloadFromGpu` could be modified to pass `textureSrc->getPixelFormat()` instead of `mPixelFormatFamily` to `VulkanMappings::getImageAspect`.
3. If I understand correctly, the whole purpose of pixel format families is just for the benefit of the D3D11 render system.  So maybe the `PixelFormatGpuUtils::getFamily` call could be removed from `TextureGpuManager::createAsyncTextureTicket` and moved into the constructor of `D3D11AsyncTextureTicket`.

**Comment by darksylinc** [comment] 2022-08-06 01:10
- I was able to repro the validation error
 - I was unable to repro the `Ogre: Depth values are all == 0` but this is normal because when we're doing Vulkan incorrectly, some GPUs and/or drivers will behave as intended while others do whatever they want.

I pushed a fix. Let me know if this fixes your problem so we can close the ticket.

**Comment by jwwalker** [comment] 2022-08-06 16:46
@darksylinc Yes, this fixes the problem for me, thanks!

**Closed** 2022-08-06 17:11 UTC
