### ISSUE TITLE
Ogre Deps issues... Bitbucket & VS2019

### ISSUE THREAD

**Issue by al2950** [OGRECave/ogre-next#63] opened 2020-01-06 11:51 UTC
Just wanted to point out a couple of issues with the Ogre Deps, linked issues can be found here:

https://bitbucket.org/cabalistic/ogredeps/issues/38/vs2019-compile-issues
https://bitbucket.org/cabalistic/ogredeps/issues/39/should-this-all-be-moved-to-the-ogre-cave

**Comment by darksylinc** [comment] 2020-03-02 22:22
vs2019 & SDL: Cannot reproduce
Move to github: almost there. We've moved to github, but we haven't updated scripts nor docs

**Comment by darksylinc** [comment] 2020-07-07 16:26
OgreDeps + Bitbucket: Should be fixed by now, we've updated all link
SDL + VS2019: Fixed in upstream, we had to update to latest master (it's not a 'stable' release)

**Closed by darksylinc** 2020-07-07 16:26 UTC
